# Generated by Django 5.1.7 on 2025-05-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="idx_comment_run_commenter_time",
        ),
        migrations.RemoveIndex(
            model_name="route",
            name="idx_route_creator_name",
        ),
        migrations.RemoveIndex(
            model_name="run",
            name="idx_run_runner_date_time",
        ),
        migrations.RemoveIndex(
            model_name="run",
            name="idx_run_runner_date",
        ),
        migrations.RemoveIndex(
            model_name="run",
            name="idx_run_route_runner",
        ),
        migrations.RemoveIndex(
            model_name="runlike",
            name="idx_runlike_run_runner",
        ),
        migrations.RemoveIndex(
            model_name="runner",
            name="idx_runner_user",
        ),
    ]
